export const projects = [
  {
    title: 'Day 1',
    description: "Repository with All Chalenge Projects.",
      image: '/images/21days.gif',
      tags: ['Git', 'Github'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 0,
  },
  {
    title: 'Day 2',
    description:"Custom a Hello World.",
    image: '/images/hello.gif',
    tags: ['HTML', 'CSS'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 1,
  },
  {
    title: 'Day 3',
    description: "Animated button.",
      image: '/images/button.gif',
      tags: ['HTML', 'CSS', 'javaScript'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 2,
  },
  {
    title: 'Day 4',
    description: "Calculator.",
    image: '/images/calculator.gif',
    tags: ['React', 'CSS'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 3,
  },
  {
    title: 'Day 5',
    description: "Custom a 404 Error Page.",
      image: '/images/space.gif',
      tags: ['HTML', 'CSS'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 4,
  },
  {
    title: 'Day 6',
    description: "Card with Glassmorphism Effect.",
      image: '/images/card.gif',
      tags: ['HTML', 'CSS', 'JavaScript'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 5,
  },
  {
    title: 'Day 7',
    description: "Create a counter.",
      image: '/images/counter2.gif',
      tags: ['React', 'Node', 'CSS'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 6,
  },
  {
    title: 'Day 8',
    description: "Toggle that changes the light to dark.",
      image: '/images/dark-p.gif',
      tags: ['HTML', 'CSS', 'JavaScript'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 7,
  },
  {
    title: 'Day 9',
    description: "Create a loading animation.",
      image: '/images/load.gif',
      tags: ['HTML', 'CSS', 'JavaScript'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 8,
  },
  {
    title: 'Day 10',
    description: "Use the javaScript Particle.js lib.",
      image: '/images/partic.gif',
      tags: ['HTML', 'JavaScript'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 9,
  },
  {
    title: 'Day 11',
    description: "Create a login form layout.",
      image: '/images/login.gif',
      tags: [ 'React', 'CSS'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 10,
  },
  {
    title: 'Day 12',
    description: "Develop an image gallery.",
      image: '/images/gallerr.gif',
      tags: ['HTML', 'CSS', 'JavaScript'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 11,
  },
  {
    title: 'Day 13',
    description: "Develop a responsive menu.",
      image: '/images/menu.gif',
      tags: ['React', 'Node', 'CSS'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 12,
  },
  {
    title: 'Day 14',
    description: "Create a quiz form.",
      image: '/images/quizz.gif',
      tags: ['React', 'Node', 'CSS'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 13,
  },
  {
    title: 'Day 15',
    description: "Develop a website that displays a showcase of fictitious e-commerce products, with names, prices, and images.",
      image: '/images/comercio.gif',
      tags: ['HTML', 'CSS', 'JavaScript'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 14,
  },
  {
    title: 'Day 16',
    description: "Develop a website by creating a public API.",
      image: '/images/movie.gif',
      tags: ['React', 'Node', 'CSS'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 15,
  },
  {
    title: 'Day 17',
    description: " website that captures keyboard events and displays on the screen.",
      image: '/images/key.gif',
      tags: ['HTML', 'CSS', 'JavaScript'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 16,
  },
  {
    title: 'Day 18',
    description: "Develop a random password generator.",
      image: '/images/pass.gif',
      tags: ['HTML', 'CSS', 'JavaScript'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 17,
  },
  {
    title: 'Day 19',
    description: "Develop a website that generates random images using the unsplash API.",
      image: '/images/paisage.gif',
      tags: ['HTML', 'CSS'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 18,
  },
  {
    title: 'Day 20',
    description: "Emoji picker website, when selecting the emoji it is copied to the clipboard.",
      image: '/images/emo.gif',
      tags: ['HTML', 'CSS', 'JavaScript'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 19,
  },
  {
    title: 'Day 21',
    description: "Develop a page for your portfolio.",
      image: '/images/21.gif',
      tags: ['React', 'Node', 'CSS'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 20,
  }
];